/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.RegistroEstacionamiento;
import Modelo.Auto;
import Modelo.Camion;
import Modelo.Camioneta;
import Modelo.Moto;

/**
 *
 * @author Benjamin
 */
public class Ingreso extends javax.swing.JFrame {

    /**
     * Creates new form Ingreso
     */
    public Ingreso() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblIngresar = new javax.swing.JLabel();
        txtPatente = new javax.swing.JTextField();
        lblMarca = new javax.swing.JLabel();
        txtMarca = new javax.swing.JTextField();
        optAuto = new javax.swing.JRadioButton();
        optMoto = new javax.swing.JRadioButton();
        optCamion = new javax.swing.JRadioButton();
        btnVolver = new javax.swing.JButton();
        btnIngresar = new javax.swing.JButton();
        lblModelo = new javax.swing.JLabel();
        txtModelo = new javax.swing.JTextField();
        lblTipodeVehiculo = new javax.swing.JLabel();
        lblTrabajador = new javax.swing.JLabel();
        optTrabajadorSi = new javax.swing.JRadioButton();
        optTrabajadorNo = new javax.swing.JRadioButton();
        optCamioneta = new javax.swing.JRadioButton();
        lblCarroceria = new javax.swing.JLabel();
        txtCarroceria = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lblTitulo.setFont(new java.awt.Font("Gadugi", 1, 24)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Ingresar Vehiculo");

        lblIngresar.setText("Ingrese la Patente:");

        txtPatente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPatenteActionPerformed(evt);
            }
        });
        txtPatente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPatenteKeyTyped(evt);
            }
        });

        lblMarca.setText("Marca:");

        txtMarca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMarcaKeyTyped(evt);
            }
        });

        buttonGroup1.add(optAuto);
        optAuto.setSelected(true);
        optAuto.setText("Auto");
        optAuto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                optAutoMouseClicked(evt);
            }
        });

        buttonGroup1.add(optMoto);
        optMoto.setText("Moto");
        optMoto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                optMotoMouseClicked(evt);
            }
        });
        optMoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optMotoActionPerformed(evt);
            }
        });

        buttonGroup1.add(optCamion);
        optCamion.setText("Camión");
        optCamion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                optCamionMouseClicked(evt);
            }
        });

        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        btnIngresar.setText("Ingresar");
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });

        lblModelo.setText("Modelo:");

        txtModelo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtModeloKeyTyped(evt);
            }
        });

        lblTipodeVehiculo.setText("Tipo de Vehiculo:");

        lblTrabajador.setText("Trabajador:");

        buttonGroup2.add(optTrabajadorSi);
        optTrabajadorSi.setText("Si");
        optTrabajadorSi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                optTrabajadorSiMouseClicked(evt);
            }
        });

        buttonGroup2.add(optTrabajadorNo);
        optTrabajadorNo.setSelected(true);
        optTrabajadorNo.setText("No");
        optTrabajadorNo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                optTrabajadorNoMouseClicked(evt);
            }
        });

        buttonGroup1.add(optCamioneta);
        optCamioneta.setText("Camioneta");
        optCamioneta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optCamionetaActionPerformed(evt);
            }
        });

        lblCarroceria.setText("Carroceria");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnVolver)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnIngresar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(68, 68, 68)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lblTrabajador)
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(optTrabajadorSi)
                                                .addGap(32, 32, 32)
                                                .addComponent(optTrabajadorNo))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(optAuto, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(optMoto, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(optCamion, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(lblMarca)
                                                        .addComponent(lblIngresar))
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addGap(67, 67, 67)
                                                        .addComponent(lblModelo)))
                                                .addGap(32, 32, 32))
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(lblCarroceria)
                                                .addComponent(lblTipodeVehiculo)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtModelo, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                                            .addComponent(txtMarca, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                                            .addComponent(txtPatente, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                                            .addComponent(txtCarroceria)))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(optCamioneta)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(22, 22, 22)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lblTitulo)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIngresar)
                    .addComponent(txtPatente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMarca)
                    .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblModelo)
                    .addComponent(txtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCarroceria)
                    .addComponent(txtCarroceria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblTipodeVehiculo)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(optAuto)
                    .addComponent(optMoto)
                    .addComponent(optCamion)
                    .addComponent(optCamioneta))
                .addGap(18, 18, 18)
                .addComponent(lblTrabajador)
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(optTrabajadorNo)
                    .addComponent(optTrabajadorSi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVolver)
                    .addComponent(btnIngresar))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtModeloKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtModeloKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtModeloKeyTyped

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed

        String patente=txtPatente.getText();
        String marca=txtMarca.getText();
        String modelo=txtModelo.getText();
        String carroceria=txtCarroceria.getText();
        System.out.println(modelo);
        if(optAuto.isSelected()){
            if(optTrabajadorNo.isSelected()){
                Auto auto=new Auto(carroceria, patente, marca, modelo, false);
                RegistroEstacionamiento.ingresarAutoCamioneta(auto);
                System.out.println("Ingresado");
            }
            else if(optTrabajadorSi.isSelected()){
                 Auto auto=new Auto(carroceria, patente, marca, modelo, true);
                RegistroEstacionamiento.ingresarAutoCamioneta(auto);
            }
        }
        else if(optCamioneta.isSelected()){
            if(optTrabajadorNo.isSelected()){
                Camioneta camioneta=new Camioneta(carroceria, patente, marca, modelo, false);
                RegistroEstacionamiento.ingresarAutoCamioneta(camioneta);
                System.out.println("Ingresado");
            }
            else if(optTrabajadorSi.isSelected()){
                 Camioneta camioneta=new Camioneta(carroceria, patente, marca, modelo, true);
                RegistroEstacionamiento.ingresarAutoCamioneta(camioneta);
                System.out.println("Ingresado");
            }
        }
        else if(optMoto.isSelected()){
            if(optTrabajadorNo.isSelected()){
                Moto moto=new Moto(carroceria, patente, marca, modelo, false);
                RegistroEstacionamiento.ingresarAutoCamioneta(moto);
                System.out.println("Ingresado");
            }
            else if(optTrabajadorSi.isSelected()){
                  Moto moto=new Moto(carroceria, patente, marca, modelo, true);
                RegistroEstacionamiento.ingresarAutoCamioneta(moto);
                System.out.println("Ingresado");
            }
        }
        else if(optCamion.isSelected()){
            if(optTrabajadorNo.isSelected()){
                Camion camion=new Camion(carroceria, patente, marca, modelo, false);
                RegistroEstacionamiento.ingresarAutoCamioneta(camion);
                System.out.println("Ingresado");
            }
            else if(optTrabajadorSi.isSelected()){
                Camion camion=new Camion(carroceria, patente, marca, modelo, true);
                RegistroEstacionamiento.ingresarAutoCamioneta(camion);
                System.out.println("Ingresado");
            }
        }
    }//GEN-LAST:event_btnIngresarActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void optCamionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_optCamionMouseClicked
        optAuto.setSelected(false);
        optMoto.setSelected(false);
        optCamion.setSelected(true);
    }//GEN-LAST:event_optCamionMouseClicked

    private void optMotoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_optMotoMouseClicked
        optAuto.setSelected(false);
        optMoto.setSelected(true);
        optCamion.setSelected(false);
    }//GEN-LAST:event_optMotoMouseClicked

    private void optAutoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_optAutoMouseClicked
        optAuto.setSelected(true);
        optMoto.setSelected(false);
        optCamion.setSelected(false);
    }//GEN-LAST:event_optAutoMouseClicked

    private void txtMarcaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMarcaKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMarcaKeyTyped

    private void txtPatenteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPatenteKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPatenteKeyTyped

    private void optTrabajadorSiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_optTrabajadorSiMouseClicked
        optTrabajadorSi.setSelected(true);
        optTrabajadorNo.setSelected(false);
    }//GEN-LAST:event_optTrabajadorSiMouseClicked

    private void optTrabajadorNoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_optTrabajadorNoMouseClicked
        optTrabajadorSi.setSelected(false);
        optTrabajadorNo.setSelected(true);
    }//GEN-LAST:event_optTrabajadorNoMouseClicked

    private void txtPatenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPatenteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPatenteActionPerformed

    private void optCamionetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optCamionetaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_optCamionetaActionPerformed

    private void optMotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optMotoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_optMotoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIngresar;
    private javax.swing.JButton btnVolver;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCarroceria;
    private javax.swing.JLabel lblIngresar;
    private javax.swing.JLabel lblMarca;
    private javax.swing.JLabel lblModelo;
    private javax.swing.JLabel lblTipodeVehiculo;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTrabajador;
    private javax.swing.JRadioButton optAuto;
    private javax.swing.JRadioButton optCamion;
    private javax.swing.JRadioButton optCamioneta;
    private javax.swing.JRadioButton optMoto;
    private javax.swing.JRadioButton optTrabajadorNo;
    private javax.swing.JRadioButton optTrabajadorSi;
    private javax.swing.JTextField txtCarroceria;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtModelo;
    private javax.swing.JTextField txtPatente;
    // End of variables declaration//GEN-END:variables
}
